# action.yml
name: 'Upload mender artifact'
description: 'Upload a mender artifact to a hosted Mender backend instance'
inputs:
  mender_user:
    description: 'username for the hosted Mender backend account to be used'
    required: true
  mender_password:
    description: 'password for the hosted Mender backend account to be used'
    required: true
  mender_uri:
    description: 'URI for the hosted Mender backend account to be used'
    required: false
    default: 'https://hosted.mender.io'
  mender_artifact:
    description: 'path of the artifact to be uploaded, relative to GITHUB_WORKSPACE'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'