# action.yml
name: 'Upload mender artifact'
description: 'Upload a mender artifact to a hosted Mender backend instance'
inputs:
  mender_pat:
    description: 'personal access token for the hosted Mender backend account to be used'
    required: true
  mender_uri:
    description: 'URI for the hosted Mender backend account to be used'
    required: false
    default: 'https://hosted.mender.io'
  mender_artifact:
    description: 'path of the artifact to be uploaded, relative to GITHUB_WORKSPACE'
    required: true
runs:
  using: "composite"
  steps:
    - id: upload_artifact
      run: |
        curl -s -X POST ${{ inputs.mender_uri }}/api/management/v1/deployments/artifacts \
        -H 'Content-Type: multipart/form-data' \
        -H 'Accept: application/json' \
        -H "Authorization: Bearer ${{ inputs.mender_pat }}" \
        -F artifact=@${GITHUB_WORKSPACE}/${{ inputs.mender_artifact }}
      shell: bash
